settings:
  username: "rudra-sah00"
  commit_username: "github-actions[bot]"
  commit_email: "github-actions[bot]@users.noreply.github.com"
  commit_msg: "âš¡ Update README with recent activity"
  max_lines: 10
  readme_file: "./README.md"
  disabled_events:
    - "comments"
  date:
    text: "Last Updated:"
    format: "dd MMM yyyy - HH:mm UTC"
    timezone: "Asia/Kolkata"
  commit_name: "Recent Activity"
  url_text: "{REPO}{ID}"
  messages:
    comments: "ğŸ’¬ Commented on {ID} in {REPO}"
    issue_opened: "â—ï¸ Opened issue {ID} in {REPO}"
    issue_closed: "âœ”ï¸ Closed issue {ID} in {REPO}"
    pr_opened: "ğŸ”” Opened PR {ID} in {REPO}"
    pr_closed: "ğŸš€ Merged PR {ID} in {REPO}"
    pr_merged: "âš¡ PR {ID} merged in {REPO}"
    create_repo: "ğŸ“¦ Created new repo {REPO}"
    fork_repo: "ğŸ”± Forked {REPO}"
    wiki_create: "ğŸ“– Created wiki page in {REPO}"
    star_repo: "â­ Starred {REPO}"
    release: "ğŸ‰ Released {ID} in {REPO}"
